"""followers

Revision ID: 30626b4ea5a1
Revises: 961dd784e096
Create Date: 2023-12-16 18:24:03.564822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30626b4ea5a1'
down_revision = '961dd784e096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
